### ISSUE TITLE
Issue with shape of background data and error slitlets for the high-resolution gratings with v0.6.6

### ISSUE THREAD

**Issue by chisholmjohn** [gbrammer/msaexp#30]
Using the the latest version of the MSAEXP (0.6.6) with H-grating data produces background slitlets that have differing shapes for their data and their error (see attached image). This causes the extraction from drizzled files to fail. Any suggestions on how to address this would be great! Thank you again for the great code to reduce the data. 
<img width="1096" alt="Screen Shot 2023-03-30 at 8 54 33 AM" src="https://user-images.githubusercontent.com/75801201/228858958-72c4fba5-882e-4132-b97b-9a50e0cfceca.png">

**Comment by themiyan** [comment]
Maybe this is related to a previously fixed issue https://github.com/gbrammer/msaexp/issues/10 but now in the case of background slits?

**Comment by gbrammer** [comment]
Thanks for flagging this.  I'm pretty sure the issue is caused by a recent update where the way the filenames of the slitlet extraction files are generated / interpreted.  See [here](https://github.com/gbrammer/msaexp/blob/main/msaexp/pipeline.py#L810).  

The files have names like `jw01871001001_04105_00001_nrs1_phot.[INDEX].1871_545.fits` .  Before, `INDEX` was sort of a random number based on the order the files were created.  Now `INDEX` is a deterministic number given by the `slitlet_id`  in the MSA plan for a given target.

The array size issue then comes when the script first reads the files into a list for the original data and then reads them again into a second list used for the background subtraction.  With the filename issue, it could read those lists in a different order and the files don't match up correctly.  

I added a little script at [update_slitlet_filenames](https://github.com/gbrammer/msaexp/blob/main/msaexp/utils.py#L122) to rename older files to the new convention that hopefully would solve this.  Otherwise, I would just suggest regenerating the slitlet files from the beginning.  FYI that function isn't in the `pip` release yet.

**Comment by gbrammer** [comment]
That script should be safe to run on any version of the files, it just won't do anything if they already have the correct name.

**Comment by chisholmjohn** [comment]
Thank you for the help with this. Another way to resolve it for anyone that is having this issue is to re-reduce the files.
